import 'server-only';
import template from './community-template.json';
import { budgetSummary,planSectionLabels,type PlanBasics,type PlanResult } from './catalog';

const crcTable=Array.from({length:256},(_,n)=>{let c=n;for(let k=0;k<8;k++)c=c&1?0xedb88320^(c>>>1):c>>>1;return c>>>0;});
function crc32(data:Buffer){let crc=0xffffffff;for(const byte of data)crc=crcTable[(crc^byte)&0xff]^(crc>>>8);return(crc^0xffffffff)>>>0;}
function zip(entries:{name:string;data:Buffer}[]){const locals:Buffer[]=[];const centrals:Buffer[]=[];let offset=0;for(const entry of entries){const name=Buffer.from(entry.name,'utf8');const crc=crc32(entry.data);const header=Buffer.alloc(30);header.writeUInt32LE(0x04034b50);header.writeUInt16LE(20,4);header.writeUInt16LE(0x800,6);header.writeUInt32LE(crc,14);header.writeUInt32LE(entry.data.length,18);header.writeUInt32LE(entry.data.length,22);header.writeUInt16LE(name.length,26);locals.push(header,name,entry.data);const central=Buffer.alloc(46);central.writeUInt32LE(0x02014b50);central.writeUInt16LE(20,4);central.writeUInt16LE(20,6);central.writeUInt16LE(0x800,8);central.writeUInt32LE(crc,16);central.writeUInt32LE(entry.data.length,20);central.writeUInt32LE(entry.data.length,24);central.writeUInt16LE(name.length,28);central.writeUInt32LE(offset,42);centrals.push(central,name);offset+=header.length+name.length+entry.data.length;}const directory=Buffer.concat(centrals);const end=Buffer.alloc(22);end.writeUInt32LE(0x06054b50);end.writeUInt16LE(entries.length,8);end.writeUInt16LE(entries.length,10);end.writeUInt32LE(directory.length,12);end.writeUInt32LE(offset,16);return Buffer.concat([...locals,directory,end]);}
const escapeXml=(value:string)=>value.replace(/[\x00-\x08\x0b\x0c\x0e-\x1f]/g,'').replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('>','&gt;').replaceAll('"','&quot;').replaceAll("'",'&apos;');
export function buildCommunityHwpx(basics:PlanBasics,result:PlanResult){const budget=budgetSummary(basics);const s=result.sections;const missing='[입력 필요]';const thousand=(value:number|null)=>value===null?`${missing} 천원`:`${(value/1000).toLocaleString('ko-KR',{maximumFractionDigits:3})} 천원`;
  const fields:Record<string,string>={group:basics.group||missing,representative:basics.representative||missing,address:basics.address||missing,phone:basics.phone||missing,title:result.title,totalThousand:thousand(budget.total),grantThousand:thousand(budget.grant),contributionThousand:thousand(budget.contribution),ratioNote:`보조금 대비 자부담: ${budget.ratio===null?missing:budget.ratio+'%'} (첨부 양식: 5% 이상 필수)`,summary:[s.purpose,s.activities,s.effects].filter(Boolean).join('\n\n'),scheduleNote:`${s.schedule||missing}\n※ 첨부 양식: 2026년 10월 말까지 완료 조건 확인`,purposeWithTarget:`${s.purpose||missing}\n\n사업 대상: ${s.target||missing}`,participation:s.participation||missing,schedule:s.schedule||missing,activitiesWithEffects:`${s.activities||missing}\n\n기대효과: ${s.effects||missing}`,budgetLabel:'예산 확인',budget:s.budget||missing,groupIntro:s.groupIntro||missing,history:'[입력 필요: 실제 주요 활동 이력을 5줄 이내로 확인하여 기재]',missing};
  const preview=`${result.title}\n모임명: ${basics.group||missing}\n${Object.entries(planSectionLabels).map(([key,label])=>`${label}\n${s[key]||missing}`).join('\n\n')}\nAI 초안 — 제출 전 확인 필요`;
  const entries=template.entries.map(entry=>{let data=Buffer.from(entry.data,'base64');if(entry.name==='Contents/section0.xml'){let xml=data.toString('utf8');xml=xml.replace(/<hp:p\b([^>]*)><hp:run\b([^>]*)><hp:t>\{\{([A-Za-z]+)\}\}<\/hp:t><\/hp:run><\/hp:p>/g,(_match,pAttrs,runAttrs,key)=>{const lines=(fields[key]||missing).split(/\r?\n/).filter(line=>line.trim());return(lines.length?lines:['']).map(line=>`<hp:p${pAttrs}><hp:run${runAttrs}><hp:t>${escapeXml(line)}</hp:t></hp:run></hp:p>`).join('');});xml=xml.replace(/\{\{([A-Za-z]+)\}\}/g,(_match,key)=>escapeXml(fields[key]||missing));data=Buffer.from(xml,'utf8');}else if(entry.name==='Preview/PrvText.txt'){data=Buffer.from(preview,'utf8');}return{name:entry.name,data};});return zip(entries);}
