'use client';
import { useState } from 'react';
import { Check, Copy, Download, FileUp, LoaderCircle, Sparkles, X } from 'lucide-react';
import { experienceTools } from '@/lib/experience/catalog';
import { ExperienceIcon } from './icon';
import { saveBlob } from './plan-wizard';

const labels:Record<string,string>={title:'제목',content:'문서 내용',template:'양식',missingFields:'추가할 정보',checklist:'확인할 사항',projectName:'사업명',summary:'핵심 요약',eligibility:'신청 자격',supportDetails:'지원 내용',amount:'지원 금액',deadline:'마감일',applicationMethod:'신청 방법',requiredDocs:'필요 서류',actionItems:'다음 할 일',cautions:'유의 사항',items:'영수증 항목',totalAmount:'총금액',warnings:'확인할 부분',meetingDate:'회의 일시',location:'장소',attendees:'참석자',agenda:'안건',decisions:'결정 사항',notes:'참고 사항',minutes:'회의록',transcript:'받아쓴 내용',script:'방송 원고',estimatedSeconds:'예상 방송 시간',date:'날짜',vendor:'판매처',item:'품목',quantity:'수량',unitPrice:'단가',total:'합계',category:'분류',sourceFile:'원본 파일',task:'할 일',owner:'담당자',dueDate:'기한',topic:'안건',discussion:'논의',decision:'결정'};
function display(value:unknown):string {if(value==null||value==='')return '확인 필요';if(Array.isArray(value))return value.map(item=>display(item)).join('\n\n');if(typeof value==='object')return Object.entries(value).map(([key,item])=>`${labels[key]||key}: ${display(item)}`).join('\n');return String(value);}
export function ExperienceTool({tool}:{tool:string}) {
  const definition=experienceTools.find(item=>item.slug===tool)!;
  const [text,setText]=useState('');const[files,setFiles]=useState<File[]>([]);const[template,setTemplate]=useState('마을 공지문');const[style,setStyle]=useState('formal');const[consent,setConsent]=useState(false);const[running,setRunning]=useState(false);const[result,setResult]=useState<Record<string,unknown>|null>(null);const[error,setError]=useState('');const[message,setMessage]=useState('');
  const needsText=tool==='format'||tool==='narration';
  const maxText=tool==='narration'?3500:6000;
  const resultText=result?Object.entries(result).filter(([key])=>!['audioBase64','audioMimeType','transcript'].includes(key)).map(([key,value])=>`${labels[key]||key}\n${display(value)}`).join('\n\n'):'';
  function selectFiles(chosen:File[]){if(chosen.length>(tool==='receipt'?3:1)){setError(tool==='receipt'?'사진은 한 번에 3장까지 선택해 주세요.':'파일 1개를 선택해 주세요.');return;}if(chosen.some(file=>file.size>4*1024*1024)||chosen.reduce((sum,file)=>sum+file.size,0)>4*1024*1024){setError('체험 파일은 전체 4MB 이하로 선택해 주세요.');return;}setFiles(chosen);setError('');}
  async function run(){setRunning(true);setError('');setMessage('');try{const session=await fetch('/api/experience/session',{method:'POST'});const sp=await session.json();if(!session.ok)throw new Error(sp.error?.message||'체험을 시작하지 못했어요.');let body:BodyInit;const headers:HeadersInit={};if(needsText){headers['content-type']='application/json';body=JSON.stringify({text,template,style});}else{const form=new FormData();files.forEach(file=>form.append(tool==='receipt'?'files':'file',file));body=form;}const response=await fetch(`/api/experience/ai/${tool}`,{method:'POST',headers,body});const payload=await response.json();if(!response.ok||!payload.result)throw new Error(payload.error?.message||'자료를 정리하지 못했어요.');setResult(payload.result);}catch(cause){setError(cause instanceof Error?cause.message:'잠시 후 다시 시도해 주세요.');}finally{setRunning(false);}}
  function download(){if(!result)return;if(tool==='receipt'&&Array.isArray(result.items)){const keys=['date','vendor','item','quantity','unitPrice','total','category'];const csvCell=(value:unknown)=>{let v=String(value??'');if(/^[=+\-@\t\r]/.test(v))v=`'${v}`;return `"${v.replaceAll('"','""')}"`;};const rows=[keys.map(key=>csvCell(labels[key])).join(','),...result.items.map((item:Record<string,unknown>)=>keys.map(key=>csvCell(item[key])).join(','))];saveBlob('영수증-장부.csv',new Blob(['\ufeff'+rows.join('\r\n')],{type:'text/csv;charset=utf-8'}));}else if(tool==='narration'&&typeof result.audioBase64==='string'){saveBlob('마을-방송.mp3',new Blob([Uint8Array.from(atob(result.audioBase64),char=>char.charCodeAt(0))],{type:'audio/mpeg'}));}else saveBlob(`${definition.title}.txt`,new Blob([resultText],{type:'text/plain;charset=utf-8'}));}
  return <div style={{maxWidth:820,margin:'0 auto'}}><div className="exp-tool-heading"><span className="exp-tool-icon"><ExperienceIcon name={definition.icon}/></span><div><h1>{definition.title}</h1><p>{definition.description}</p></div></div><p className="exp-demo-notice">로그인 없이 기능별 1회 체험할 수 있어요. 실제 개인정보가 포함된 자료는 사용하지 마세요.</p>
    {needsText?<label className="exp-field">{tool==='narration'?'어떤 내용을 안내할까요?':'어떤 내용을 문서로 만들까요?'}<textarea value={text} maxLength={maxText} style={{minHeight:220}} onChange={event=>setText(event.target.value)} placeholder={tool==='narration'?'날짜, 장소, 주민에게 안내할 내용을 편하게 적어 주세요.':'메모나 초안을 편하게 적어 주세요.'}/><small>{text.length.toLocaleString()} / {maxText.toLocaleString()}자</small></label>:<><label className="exp-upload"><input type="file" className="sr-only" accept={tool==='transcribe'?'audio/mpeg,audio/mp4,audio/wav,audio/webm,.mp3,.m4a,.wav,.webm':tool==='receipt'?'image/jpeg,image/png,image/webp':'image/jpeg,image/png,image/webp,application/pdf,text/plain'} multiple={tool==='receipt'} onChange={event=>selectFiles(Array.from(event.target.files||[]))}/><FileUp size={31}/><strong>{tool==='transcribe'?'녹음 파일 선택':tool==='receipt'?'영수증 사진 선택':'공고문 파일 선택'}</strong><small>{tool==='transcribe'?'MP3 · M4A · WAV · WEBM':tool==='receipt'?'JPG · PNG · WEBP, 최대 3장':'PDF · JPG · PNG · WEBP · TXT'}<br/>전체 4MB 이하</small></label><div className="exp-file-list">{files.map((file,index)=><div key={`${file.name}-${index}`}><FileUp size={16}/><span>{file.name}</span><small>{(file.size/1024/1024).toFixed(1)}MB</small><button aria-label={`${file.name} 선택 해제`} onClick={()=>setFiles(current=>current.filter((_,i)=>i!==index))}><X size={17}/></button></div>)}</div></>}
    {tool==='format'&&<label className="exp-field" style={{marginTop:20}}>문서 종류<select value={template} onChange={event=>setTemplate(event.target.value)}>{['마을 공지문','보조금 신청서','결과보고서','공식 회의록'].map(item=><option key={item}>{item}</option>)}</select></label>}{tool==='narration'&&<label className="exp-field" style={{marginTop:20}}>방송 말투<select value={style} onChange={event=>setStyle(event.target.value)}><option value="formal">정중하고 명확하게</option><option value="friendly">따뜻하고 친근하게</option><option value="cheerful">밝고 경쾌하게</option></select></label>}
    <label className="exp-consent"><input type="checkbox" checked={consent} onChange={event=>setConsent(event.target.checked)}/><span>선택한 자료를 AI 서비스로 전달하여 처리하는 데 동의합니다.</span></label><button className="exp-primary-button" style={{width:'100%'}} disabled={running||!consent||(needsText?!text.trim():!files.length)} onClick={run}>{running?<LoaderCircle className="exp-spin" size={20}/>:<Sparkles size={19}/>} {running?'자료를 정리하고 있어요':'AI로 정리하기'}</button>
    {error&&<p className="exp-error" role="alert">{error}</p>}{message&&<p className="exp-help" role="status">{message}</p>}{running&&<p className="exp-loading" role="status">처리 중입니다. 파일 크기에 따라 잠시 걸릴 수 있어요.</p>}
    {result&&<section className="exp-output"><h2><Check size={20} style={{display:'inline',marginRight:6}}/> 정리가 끝났어요</h2>{typeof result.audioBase64==='string'&&<audio controls src={`data:audio/mpeg;base64,${result.audioBase64}`}/>} {Object.entries(result).filter(([key])=>!['audioBase64','audioMimeType','transcript'].includes(key)).map(([key,value])=><div key={key}><h3>{labels[key]||key}</h3><pre>{display(value)}</pre></div>)}<div className="exp-result-buttons"><button className="exp-primary-button" onClick={download}><Download size={18}/> 파일 받기</button><button className="exp-secondary-button" onClick={async()=>{try{await navigator.clipboard.writeText(resultText);setMessage('내용을 복사했어요.');}catch{setError('복사하지 못했어요. 파일로 내려받아 주세요.');}}}><Copy size={17}/> 내용 복사</button></div><p className="exp-help">AI 결과는 사실관계와 숫자를 확인한 뒤 사용해 주세요. 이 결과는 마을 공용 문서함에 저장되지 않습니다.</p></section>}
  </div>;
}
