'use client';
import { ChevronDown } from 'lucide-react';
import type { PlanResult } from '@/lib/experience/catalog';

export function PlanDetails({ result, onChange }: { result: PlanResult; onChange: (value: PlanResult) => void }) {
  return <>
    {!!result.scheduleRows?.length && <details className="exp-review-card"><summary>추진계획 표 · {result.scheduleRows.length}개 활동 <ChevronDown size={17}/></summary><div className="exp-detail-rows">{result.scheduleRows.map((row, index) => <fieldset key={index}><legend>활동 {index + 1}</legend>{(['name', 'when', 'content'] as const).map(key => <label className="exp-field" key={key}>{({name:'사업·활동명',when:'일정',content:'사업내용'})[key]}<textarea value={row[key]} maxLength={key === 'content' ? 1000 : key === 'when' ? 150 : 100} onChange={event => onChange({...result,scheduleRows:result.scheduleRows?.map((item,i)=>i===index?{...item,[key]:event.target.value}:item)})}/></label>)}</fieldset>)}</div></details>}
    {!!result.budgetRows?.length && <details className="exp-review-card" open><summary>비목별 예산표 · {result.budgetRows.length}개 항목 <ChevronDown size={17}/></summary><div className="exp-detail-rows">{result.budgetRows.map((row,index) => <fieldset key={index}><legend>예산 {index + 1}</legend><div className="exp-input-pair"><label className="exp-field">구분<input value={row.name} maxLength={100} onChange={event=>onChange({...result,budgetRows:result.budgetRows?.map((item,i)=>i===index?{...item,name:event.target.value}:item)})}/></label><label className="exp-field">비목<input value={row.category} maxLength={50} onChange={event=>onChange({...result,budgetRows:result.budgetRows?.map((item,i)=>i===index?{...item,category:event.target.value}:item)})}/></label></div><label className="exp-field">금액 (원)<input inputMode="numeric" value={row.amount ?? ''} maxLength={11} placeholder="견적 확인 후 입력" onChange={event=>{const value=event.target.value.replace(/\D/g,'');onChange({...result,budgetRows:result.budgetRows?.map((item,i)=>i===index?{...item,amount:value?Number(value):null}:item)});}}/></label><label className="exp-field">산출기초 · 단가 × 인원·수량 × 횟수<textarea value={row.basis} maxLength={1000} onChange={event=>onChange({...result,budgetRows:result.budgetRows?.map((item,i)=>i===index?{...item,basis:event.target.value}:item)})}/></label></fieldset>)}</div></details>}
  </>;
}
